### ISSUE TITLE
Home text translation

### ISSUE THREAD

**Issue by mcristaldo** [jfoclpf/autocosts#47]
When you select a country on the home page, the titile "Automobile costs calculator" change depending on the language, but the text below it remains in english always.
I know it would need a lot of new strings for every language, so in that case I think the title should be in english always so we're consistent, otherwise it looks a bit weird seeing the title in the language/country selected but the text below will be in english always.
What do you t
![captura de pantalla 2018-07-25 17 48 31](https://user-images.githubusercontent.com/11855774/43226615-b61ff582-9032-11e8-82d2-f88ca28cc875.png)
![captura de pantalla 2018-07-25 17 48 21](https://user-images.githubusercontent.com/11855774/43226617-b647ef10-9032-11e8-9c74-844ac57d8e03.png)

hink?

**Comment by jfoclpf** [comment]
Hi @mcristaldo I prefer to let like it is now, since I will get further translation strings in the near future. We need to fully finish the site first, and then I assemble all the further needed strings to request for translators. But for now we finish the site, to evaluate _all_ the further needed strings. Then for Spanish we have you already and for other languages I will assemble translators accordingly.
