### ISSUE TITLE
Too high numbers allowed in some fields

### ISSUE THREAD

**Issue by NCCLPF** [jfoclpf/autocosts#88]
In some fields is allowed to write too high numbers. I found at least a case where the number is limited: "Vehicle inspection (MOT test) - How many times have you taken your car to vehicle inspection?" in "1. Standing costs".

**Comment by jfoclpf** [comment]
@mcristaldo what do you think about this issue?
Should we limit the maximum amount for certain fields, like costs of the car os yearly salary?

**Comment by jfoclpf** [comment]
user should be able to put as high numbers as he/she wishes because that's not a common mistake and it would be hard to validate, since the calculator allows many different currencies with different conversions, and many different types of fields, for example the cost of automobile acquisition has a number many times higher than costs of inspection.

**Comment by mcristaldo** [comment]
Hi Joao, 
Totally agree on your last comment.
