### ISSUE TITLE
Button "Next" before the field "Maintenance"

### ISSUE THREAD

**Issue by NCCLPF** [jfoclpf/autocosts#89]
As it fills the fields, the button "Next" appears at the end. Nevertheless, I have found a case where it doesn't happen. Filling these fields: 
 - "2. Running costs - Petrol, diesel, LPG, electricity - Calculations based on - Mi - Considering you drive to work? - Yes", and 
- the subsequent ones, next to "Average price you pay for the fuel" 
it appears the button "Next" before "Maintenance".

**Comment by jfoclpf** [comment]
This is working. 

I suppose you refer to this **orange Next** button:

![image](https://user-images.githubusercontent.com/3984909/50729888-24894380-1142-11e9-89fa-79c410511804.png)

The button is supposed to appear there, before **Maintenance**, because it is the button correspondent to the whole section **fuel**, and thus it appears at the end of section **fuel**.

That orange button "next" disappears 
 - right after the mouse clicks on some other area, for example, another field; or 
 - by clicking on the button itself, or
 - by pressing Enter or TAB  

![image](https://user-images.githubusercontent.com/3984909/50729897-5dc1b380-1142-11e9-99c9-3898d09d23d4.png)


@NCCLPF if you think the error still applies kindly tell me that I open the issue
Thanks

@mcristaldo just kindly re-check and re-confirm that this section is working properly
Thanks

I'll close the issue, but further comments are still possible. I re-open the issue if appropriate.

**Comment by jfoclpf** [comment]
thanks @mcristaldo
